FROM mintplexlabs/anythingllm:latest

USER root

ENV STORAGE_DIR="/app/server/storage"

RUN mkdir -p /app/server/storage && \
    touch /app/server/storage/anythingllm.db && \
    chown -R anythingllm:anythingllm /app/server/storage

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER anythingllm

ENTRYPOINT ["/entrypoint.sh"]
